branches:
  only:
    - master

language: python
python:
  - "2.7"
  - "3.5"

env:

  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=50000  TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=50000  TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=50000  TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=50000

  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=131072  TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=131072  TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=131072  TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=131072

  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=1000000  TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=1000000  TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=1000000  TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=1000000

  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=1048576  TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=1048576  TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=1048576  TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=1048576

# NELEMS=something arbitrary that is not divisible 
# by any of the default buffer/spacing sizes 
  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=2000000  TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=2000000  TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=2000000  TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=2000000
  
# NELEMS=16777216 ~ 128MB
  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=16777216 TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=16777216 TEST_PATTERN="test_readbuf_spacing_sizes"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=16777216 TEST_PATTERN="test_seek_then_read_block"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=16777216

# NELEMS=268435456 ~ 2GB
  - TEST_SUITE=zran_test         NITERS=5000 NELEMS=268435456 TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block" EXTRA_ARGS="--use_mmap"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=268435456 TEST_PATTERN="test_readbuf_spacing_sizes"                                       EXTRA_ARGS="--use_mmap"
  - TEST_SUITE=zran_test         NITERS=500  NELEMS=268435456 TEST_PATTERN="test_seek_then_read_block"                                        EXTRA_ARGS="--use_mmap"
  - TEST_SUITE=indexed_gzip_test NITERS=5000 NELEMS=268435456                                                                                 EXTRA_ARGS="--use_mmap"

# NELEMS=805306368 ~ 6GB (for testing 64 bit support)
  - TEST_SUITE=zran_test         NITERS=1000 NELEMS=805306368 TEST_PATTERN="not test_readbuf_spacing_sizes and not test_seek_then_read_block" EXTRA_ARGS="--use_mmap"
  - TEST_SUITE=zran_test         NITERS=50   NELEMS=805306368 TEST_PATTERN="test_readbuf_spacing_sizes"                                       EXTRA_ARGS="--use_mmap"
  - TEST_SUITE=zran_test         NITERS=50   NELEMS=805306368 TEST_PATTERN="test_seek_then_read_block"                                        EXTRA_ARGS="--use_mmap"
  - TEST_SUITE=indexed_gzip_test NITERS=1000 NELEMS=805306368                                                                                 EXTRA_ARGS="--use_mmap"

install: "pip install -r requirements.txt"

script:
  - python setup.py install
  - python setup.py test --addopts "-v -s -m \"$TEST_SUITE\" -k \"$TEST_PATTERN\" --nelems \"$NELEMS\" --niters \"$NITERS\"          $EXTRA_ARGS"
  - python setup.py test --addopts "-v -s -m \"$TEST_SUITE\" -k \"$TEST_PATTERN\" --nelems \"$NELEMS\" --niters \"$NITERS\" --concat $EXTRA_ARGS"
